Magento 2.4.* fix
opengento/magento2-downgrade-ee-ce pull request #7
Opened 2021-11-18 15:43 UTC by kylianleemkuil

+ Renamed some keys for Magento 2.4.*
+ Deleted some Constraints for Magento 2.4.*
+ Added checks for doubles in tables

2021-11-18 16:12 UTC, thomas-kl1 commented
I'm going to review this later tonight! Thanks for contributing!! :)

2021-11-18 21:00 UTC, thomas-kl1 requested changes
Overall looks fine to me :)
Could you check why you removed the drop on row_id column in some cases?

2021-11-19 09:51 UTC, kylianleemkuil commented on scripts/product.sql
> -    DROP COLUMN `row_id`;
My bad deleted that for my own test reasons.

2021-11-19 09:51 UTC, kylianleemkuil commented on scripts/product.sql
> -    DROP COLUMN `row_id`;
My bad deleted that for my own test reasons.

2021-11-19 09:51 UTC, kylianleemkuil commented on scripts/product.sql
> -    DROP COLUMN `row_id`;
My bad deleted that for my own test reasons.

2021-11-19 09:51 UTC, kylianleemkuil commented on scripts/product.sql
> -    DROP COLUMN `row_id`;
My bad deleted that for my own test reasons.

2021-11-19 09:58 UTC, closed without merging

2021-11-19 09:58 UTC, kylianleemkuil commented
I will make a new pull request

2021-11-19 10:17 UTC, thomas-kl1 commented
@kylianleemkuil every new commits you push to your branch used in this PR will be taken. So you don't need to open a new PR